# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0059_merge_20170914_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePreprintProviderWhitelisted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(blank=True, default=None, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
