# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0076_action_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePreprintProviderWhitelisted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(blank=True, default=None, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
