# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0077_sharepreprintproviderwhitelisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepreprintproviderwhitelisted',
            name='provider_name',
            field=models.CharField(blank=True, default=None, max_length=200, unique=True),
        ),
    ]
